-- Corrected SQL for MySQL / MariaDB
CREATE DATABASE IF NOT EXISTS NextGEN_TechHub;
USE NextGEN_TechHub;

CREATE TABLE IF NOT EXISTS Contact (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Message TEXT NOT NULL,
    SubmittedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS TeamMembers (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Bio TEXT,
    JoinedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Events_Register (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    EventName VARCHAR(150) NOT NULL,
    Project TEXT,
    SubmittedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
