CREATE DATABASE NextGEN_TechHub;
USE NextGEN_TechHub;
CREATE TABLE Contact (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Message TEXT NOT NULL,
    SubmittedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
);

CREATE TABLE TeamMembers (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Bio TEXT,
    JoinedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
);

CREATE TABLE Events_Register (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    EventName VARCHAR(150) NOT NULL,
    Project TEXT NOT NULL,
    SubmittedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
);